CREATE OR REPLACE
FUNCTION       "FN_GETRCPT_AMT" (P_RR_NO VARCHAR2, P_BILL_DT DATE,P_BILL_NO VARCHAR2) RETURN NUMBER IS

V_RCPT_AMT NUMBER:='0';

BEGIN
           /*SELECT SUM(NVL(RP_AMT_PAID,0))  INTO V_RCPT_AMT
           FROM RCPT_PYMNT
 		   WHERE RP_PURPOSE_KEY=P_RR_NO AND EXISTS ( SELECT 'X' FROM CUSTBILL_RCPT_BREAKUP WHERE  CRB_BILL_DT=P_BILL_DT AND CRB_BILL_NO=P_BILL_NO AND CRB_DETL_FROM='01'
		   AND CRB_RR_NO=RP_PURPOSE_KEY
		   AND CRB_RCPT_DETL=TO_CHAR(RP_RCPT_DT,'YYYYMMDD')||'~'||RP_RCPT_NO||'~'||RP_CASH_COUNTR_NO);*/
		   
		   /*SELECT SUM(NVL(RP_AMT_PAID,0))  INTO V_RCPT_AMT
           FROM CUSTBILL_RCPT_BREAKUP,RCPT_PYMNT
 		   WHERE RP_PURPOSE_KEY=P_RR_NO  AND CRB_RR_NO=RP_PURPOSE_KEY AND CRB_BILL_DT=P_BILL_DT AND CRB_BILL_NO=P_BILL_NO AND CRB_DETL_FROM='01'
		   AND CRB_RCPT_DETL=TO_CHAR(RP_RCPT_DT,'YYYYMMDD')||'~'||RP_RCPT_NO||'~'||RP_CASH_COUNTR_NO;*/
		   
			SELECT SUM(NVL(RP_AMT_PAID,0)) INTO V_RCPT_AMT
			FROM RCPT_PYMNT
			WHERE EXISTS
			(SELECT 1 FROM CUSTBILL_RCPT_BREAKUP WHERE CRB_RR_NO = P_RR_NO AND CRB_BILL_DT = P_BILL_DT AND CRB_BILL_NO = P_BILL_NO AND CRB_DETL_FROM='01'
			AND CRB_RCPT_DT = RP_RCPT_DT
			AND CRB_RCPT_DETL=TO_CHAR(RP_RCPT_DT,'YYYYMMDD')||'~'||RP_RCPT_NO||'~'||RP_CASH_COUNTR_NO);
		   

	    	RETURN NVL(V_RCPT_AMT,0);
END FN_GETRCPT_AMT ; 

 

 

/