CREATE OR REPLACE
PACKAGE "PKG_CASH" IS
	--=============================================================================================
	--	WRITTEN BY				:	RAVI KUMAR
	---------------	MODIFICATION	HISTORY -------------------------------------------------------
	--	VERSION NO				:	1.00
	--	MODIFIED DATE			:   14-DEC-2014
	--	MODIFICATION PURPOSE 	:	FOR GET RCPT DETILS
	----------------------------------------------------------------------------------------------
	--===================================================================================
	--  PROCEDURES TO GET_RCPT_DETIALS
	--=================================================================================== 
	PROCEDURE GET_RCPT_DETIALS(P_TYPE VARCHAR2,P_RR_NO VARCHAR2,P_RCPT_DT VARCHAR2,P_RCPT_NO VARCHAR2,P_CNTR_NO VARCHAR2,P_PURPOSE VARCHAR2,
							   P_CHQ_DD_DT VARCHAR2,P_CHQ_DD_NO VARCHAR2,P_BANK VARCHAR2,P_LIMIT NUMBER,CUR OUT SYS_REFCURSOR);
							   
	PROCEDURE GET_RCPT_POSTED_DETAILS(P_RCPT_DT VARCHAR2,P_RCPT_NO VARCHAR2,P_CNTR_NO VARCHAR2,CUR OUT SYS_REFCURSOR);
	
	PROCEDURE GET_LIST_OF_PAYMENTS(P_RR_NO VARCHAR2,P_NO_OF_MONTHS NUMBER DEFAULT 12,P_FROM_DT VARCHAR2,P_TO_DT VARCHAR2,CUR OUT SYS_REFCURSOR);
	
	PROCEDURE GET_RCPT_DETIALS_FOR_POST(P_LOCTION_CD VARCHAR2,P_RCPT_DT VARCHAR2,P_CNTR_NO VARCHAR2,CUR OUT SYS_REFCURSOR); 
	
	PROCEDURE INSERT_CHEQUE_MASTER (CUR OUT SYS_REFCURSOR,P_CHQ_DD_NO VARCHAR2, P_CHQ_DD_DT VARCHAR2, P_DRAWN_BANK VARCHAR2, P_RCPT_DT VARCHAR2, P_PYMNT_MD VARCHAR2, P_CHQ_DD_AMT VARCHAR2, P_USRID VARCHAR2);
	
	PROCEDURE INSERT_CHEQUE_MASTER_HRT (CUR OUT SYS_REFCURSOR,P_CHQ_DD_NO VARCHAR2, P_CHQ_DD_DT VARCHAR2, P_DRAWN_BANK VARCHAR2, P_RCPT_DT VARCHAR2, P_PYMNT_MD VARCHAR2, P_CHQ_DD_AMT VARCHAR2, P_USRID VARCHAR2);
	
	PROCEDURE INSERT_RCPT_DETIALS(CUR OUT SYS_REFCURSOR,P_TRANSACTION_ID VARCHAR2,P_RCPT_DT VARCHAR2, P_CASH_COUNTR_NO VARCHAR2, P_PURPOSE VARCHAR2,P_PURPOSE_KEY VARCHAR2, P_PYMNT_MD VARCHAR2, P_AMT_PAID VARCHAR2,
                                                    P_PAYEE_NAME VARCHAR2, P_RMKS VARCHAR2, P_BCM_CHQ_DD_NO VARCHAR2, P_BCM_CHQ_DD_DT VARCHAR2, P_BCM_DRAWN_BANK VARCHAR2, P_USRID VARCHAR2); 
                                                    
    PROCEDURE INSERT_RCPT_DETIALS_HRT(CUR OUT SYS_REFCURSOR,P_TRANSACTION_ID VARCHAR2,P_RCPT_NO VARCHAR2,P_RCPT_DT VARCHAR2, P_CASH_COUNTR_NO VARCHAR2, P_PURPOSE VARCHAR2,P_PURPOSE_KEY VARCHAR2, P_PYMNT_MD VARCHAR2, P_AMT_PAID VARCHAR2,
                                                    P_PAYEE_NAME VARCHAR2, P_RMKS VARCHAR2, P_BCM_CHQ_DD_NO VARCHAR2, P_BCM_CHQ_DD_DT VARCHAR2, P_BCM_DRAWN_BANK VARCHAR2, P_USRID VARCHAR2);
                                                    
    PROCEDURE GET_PRINT_RCPTS(CUR OUT SYS_REFCURSOR,P_TRANSACTION_ID VARCHAR2);
    
    PROCEDURE GET_CASH_COUNTER_SUMMARY(CUR OUT SYS_REFCURSOR,P_RCPT_DT VARCHAR2,P_CNTR_NO VARCHAR2);
    
    PROCEDURE GET_PURPOSEWISE_REPORTS(CUR OUT SYS_REFCURSOR, P_LOCTION_CD IN VARCHAR2, P_CNTR_NO IN VARCHAR2, P_FROM_DT IN VARCHAR2, P_TO_DT IN VARCHAR2, P_HEADER IN BOOLEAN);
    
  
END PKG_CASH;

/